### PR TITLE
Rename Serbo-Croatian to Serbian

### PR DESCRIPTION
**Pull request by kkogovsek**
Renaming counter style from Serbo-Croatian to Serbian in samples.
 
Croatian language doesn't use Cyrillic script and use of term Serbo-Croatian is outdated and not accurate.

+@Aldinco
> Historically that name was used to refer to languages spoken in the former Yugoslavia but due to political as well as linguistic developments, there has been a shift towards recognising the distinct languages of the region. Today, it’s preferable to use the separate names of the languages in order to reflect their unique characteristics and cultural identities. I don’t think its wrong to keep it as is, I just think there is a more inclusive alternative.

***
<a href="https://pr-preview.s3.amazonaws.com/kkogovsek/predefined-counter-styles/pull/57.html" title="Last updated on Jun 8, 2023, 9:11 AM UTC (5455e02)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/predefined-counter-styles/57/a20738a...kkogovsek:5455e02.html" title="Last updated on Jun 8, 2023, 9:11 AM UTC (5455e02)">Diff</a>

### CODE REVIEW

**Comment by r12a** [comment]
@kkogovsek thanks for suggesting this change.  I agree that we should bring this up to date. The one thing i wanted to just check was whether the characters listed and their order still applies for Serbian users, without changes (ie. are Serbs still using the exact same alphabetic numbering as was used for Serbo-Croatian, given the shift in regional use and the progression of time).  Do you know?

**Comment by kkogovsek** [comment]
It seems so to me. I found [this mapping](http://daveanderson.me.uk/srpski/srpskicards1/cyrillic.html) (although 10 years old) which is the same as what's in this document but I haven't seen anything disputing it or changing in the recent years.

The special case with Serbian is that it uses both Latin and Cyrillic so I'm wondering if it should be `upper-serbian-cyrillic` or is `upper-serbian` enough?

**Comment by r12a** [comment]
I believe that Serbian is written by default in cyrillic, so then i think it would be fine to call these styles `upper-serbian`.  If we need to make a distinction between Serbian and Latin alphabets,  then we can call the alternative `upper-serbian-latin`.  Any objection?

**Comment by r12a** [comment]
I have a couple of things up in the air wrt the ready-made counter styles doc, and i'd like to just check where i'm up to before merging this.  Hopefully, it won't take too long, as i'm working hard to bring that work to the top of my to do list.

**Comment by r12a** [comment]
Thanks for the PR !

**Pull request merged**
